config/routes.rb
Texbin::Application.routes.draw do

  scope "/docs" do

    # Processes a document given its id
    get "/:id" => "documents#index", as: "document"

    # Adds a new document
    put "/" => "documents#save", as: "put_document"
  end

  # Help
  get "/help" => "welcome#help", as: "help"

  # Home page
  root "welcome#index"
end

app/models/concerns/carrier_wave/tex_processor.rb
module CarrierWave
  module TexProcessor
    extend ActiveSupport::Concern

    module ClassMethods
      def convert(format)
        process convert: format
      end
    end

    def convert(format)
      processors = {
        pdf: DocumentPdfProcessor.new
      }

      processors[format].process!(current_path) { |tmpdir|
        model.upload.file.copy_to tmpdir
        prepare_bundle!(tmpdir) if model.bundle?
      }

      @format = format
    end

    private

    def prepare_bundle!(dir)
      zip = Zip::File.open current_path

      zip.find_all.each { |f|
        f.extract "#{dir}/#{f.name}"
      }
    end
  end
end

app/models/document.rb
# -*- coding: utf-8 -*-

class Document
  include Mongoid::Document

  # Uploaded file added to attr_accessible to avoid mass assignment problems
  mount_uploader  :upload, DocumentUploader

  validates :upload, presence: true
  validate  :upload_file_size, if: :upload?
  validate  :bundle_structure, if: :bundle?

  after_validation :remove_invalid_document_upload

  def article?
    upload.file && !!(File.basename(upload.file.path) =~ /\.tex$/)
  end

  # Bundles are not supported yet. I'll get back to this sometime

  def bundle?
    upload.file && !!(File.basename(upload.file.path) =~ /\.zip$/)
  end

  private

  def upload_file_size
    return unless upload.file

    limit = Rails.configuration.file_size_limit

    errors.add(:upload, "is too big") if
      upload.file.size > limit
  end

  def bundle_structure
    return unless upload.file

    begin
      zip = Zip::File.open upload.file.path

      # Look for the main .tex file
      article = zip.find_entry "article.tex"

      errors.add(:upload, "is not a valid bundle") if
        article == nil
    rescue Zip::ZipError
      errors.add :upload, "is not a valid ZIP file"
    end
  end

  def remove_invalid_document_upload
    remove_upload! if errors.present?
  end
end

app/models/document_pdf_processor.rb
class DocumentPdfProcessor < DocumentProcessor

  def process_document!(dir, input_filename)
    basename = File.basename input_filename, ".tex"
    log_file = basename.chomp(File.extname(basename)) + ".log"

    # Convert the document directly to .pdf
    cmd = ["pdflatex"] + Rails.configuration.latex_default_options + [input_filename]
    run_command dir, cmd, log_file

    # Return the input filename with .pdf extension
    basename + ".pdf"
  end
end

app/models/document_processor.rb
require 'fileutils'

class DocumentProcessor

  def process!(input_filename, &block)
    content = nil

    Dir.mktmpdir { |dir|

      # The caller uses a block to add all required files to the
      # temporary directory before it can be processed
      block.call(dir) if block_given?

      # Delegates the building logic to a template method
      output_file = process_document! dir, input_filename

      # Moves output file to the final location
      FileUtils.mv "#{dir}/#{output_file}", input_filename
    }

    content
  end

  def run_command(chdir, cmd, log_file=nil)

    # Do not leak TeX stdout to our app
    _, pipe_out = IO.pipe

    pid = spawn({}, *cmd, chdir: chdir, out: pipe_out)

    begin
      Timeout.timeout(Rails.configuration.process_timeout) {
        Process.waitpid2(pid)
        pipe_out.close

        log = log_file ? File.new("#{chdir}/#{log_file}", "r").read : "TeX error"
        raise Error.new(log) if $?.exitstatus != 0
      }
    rescue Timeout::Error
      Process.kill("KILL", pid)
      raise Timeout::Error.new("Process timeout")
    end
  end

  def process_document!(dir)
    # Should be implemented by the subclasses
  end

  class Error < StandardError;end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Mongoid::Errors::DocumentNotFound, with: :record_not_found
  rescue_from ActionController::RoutingError, with: :record_not_found

  def record_not_found
    render text: "Not found.", status: :not_found
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  rescue_from DocumentProcessor::Error, with: :handle_tex_error
  rescue_from Timeout::Error,           with: :handle_timeout_error

  def save
    @new_doc = Document.new upload: params[:file]

    if @new_doc.save
      flash[:created] = @new_doc._id
      redirect_to root_path
    else
      flash[:error] = "#{@new_doc.errors[:upload].first}"
      redirect_to root_path
    end
  end

  def index
    redirect_to document.upload_url, status: :moved_permanently
  end

  private

  def document
    @document ||= Document.find params[:id]
  end

  def handle_timeout_error(err)
    @error = err
    render "errors/timeout", formats: [:html], content_type: "text/html", status: :request_timeout
  end

  def handle_tex_error(err)
    @error = err
    render "errors/tex_process", formats: [:html], content_type: "text/html", status: :unprocessable_entity
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    id = flash[:created]
    @doc_url = document_url(id: id) if id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>

  <%= yield :head %>
</head>
<body>
  <div class="page-wrapper">
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </div>

  <%= render "shared/footer" %>
</body>
</html>

app/views/shared/_big_title.html.erb
<div class="row title">
  <div class="col-md-12">
    <h1><%= title %></h1>

    <p class="tagline <%= tagline_size %>">
      <%= tagline %>
    </p>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul class="menu">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Help", help_path %></li>
  </ul>

  <div class="copyright">
    built by <a href="http://github.com/danielfm">danielfm</a> &copy; <%= Time.now.year %>
  </div>
</div>

app/views/shared/_small_title.html.erb
<div class="title small">
  <h1><%= link_to "TeXBin.", root_path %></h1>
</div>

app/views/welcome/help.html.erb
<% content_for :title, "Help - TeXBin" %>

<%= render "shared/small_title" %>

<%= render partial: "shared/big_title", locals: {
  title: "Help.",
  tagline_size: "big",
  tagline: ""
} %>

<div class="row text">
  <div class="col-md-12">
    <h2>What Is TeXBin?</h2>

    <p>
      Think of TeXBin as being a Pastebin dedicated to <span class="tex">TeX</span>; it is a
      magical place where you can submit a <code>.tex</code> file and get back a public URL
      to its glorious PDF.
    </p>

    <p>
      TeXBin is an open source project. Feel free to create your own private TeXBin server, change
      the code, or do anything you want with it. The source code can be found at
      <a href="http://github.com/danielfm/texbin">GitHub</a>.
    </p>

    <h2>Submitting A Document.</h2>

    <p>
      If you have a <code>.tex</code> file you need to share with other people - an article
      draft or a math proof, for instance - why bother generating the PDF and hosting the
      file yourself? Just submit it to TeXBin.
    </p>

    <h2>Common Errors.</h2>

    <h3>It Says The Document I Submitted Is Invalid.</h3>

    <p>
      First, make sure the file has the <code>.tex</code> extension.
    </p>

    <p>
      If you are still unable to post it, make sure the file is not too big. Currently,
      the resulting file size limit is <%= number_to_human_size Rails.configuration.file_size_limit %>,
      which should be more than enough for articles and small documents. No, we don't want
      to typeset your thousand-pages book. :-)
    </p>

    <h3>It Says TeX Could Not Process My Document.</h3>

    <p>
      If the <span class="tex">TeX</span> processor finds an error in your document, this page
      will help you find what went wrong by displaying the output log. Just read it carefully
      to spot the problem, fix it, and submit the fixed document.
    </p>

    <p>
      If you found no problem in the code itself, you're probably using a package not supported
      by our server. Read the error log carefully to be sure. In that case, we're sorry to inform
      that there's nothing we can do; your document is just too fancy for us.
    </p>

    <h3>It Says The Request Was Interrupted.</h3>

    <p>
      If a document takes too long to process, the request is interrupted so other users are not
      affected. It's probably nothing, just try again a few moments later.
    </p>
  </div>
</div>

app/views/welcome/index.html.erb
<% content_for :title, "TeXBin" %>

<%= render partial: "shared/big_title", locals: {
  title: "TeXBin.",
  tagline_size: "small",
  tagline: "The easiest way to share <span class='tex'>TeX</span> documents with the world.".html_safe
} %>

<div class="row upload">
  <div class="col-12-md">
    <%= form_tag put_document_path, method: :put, multipart: true do %>
      <div type="button" class="btn btn-primary btn-lg">
        <span class="glyphicon glyphicon-open"></span>
        Select a .tex file to share...
        <input type="file" name="file" />
      </div>

      <% if flash[:error] %>
        <p class="msg text-danger">
          <strong>Error:</strong> <%= flash[:error] %>
        </p>
      <% elsif flash[:created] %>
        <p class="msg">
          <strong>Success!</strong> Document available at:<br/>
          <%= link_to @doc_url, @doc_url, target: "_blank" %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>